#!/bin/bash
#
set -x
livepath="/home/yacoma/web/auth-boilerplate/private/auth-boilerplate"
while read oldrev newrev ref
do
        branch=`echo $ref | cut -d/ -f3`
        if [[ "master" == "$branch" ]]; then
                git --work-tree=$livepath checkout -f $branch
                cd $livepath
                make deploylive
                echo 'Changes pushed live.'
        fi
done
cd /home/yacoma/git/auth-boilerplate.git
